version: '3.2'

services:
  frontend:
    volumes:
      - ./images:/app/public
    build:
      context: frontend/
      dockerfile: Dockerfile
    ports: 
      - "8080:8080"
  backend:
    build:
      context: backend/
      dockerfile: Dockerfile
    ports: 
      - "3000:3000"
  db:
    image: mysql:8.0.25
    restart: always
    container_name: mysql
    ports: 
      - "3308:3306"
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/data:/var/lib/mysql
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=db
      - MYSQL_ROOT_PASSWORD=a1234567
    
    
